"""final database version

Revision ID: 823708a887cd
Revises: d60f2ada0927
Create Date: 2024-10-22 17:41:59.190731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '823708a887cd'
down_revision = 'd60f2ada0927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        # Drop foreign key constraint first
        batch_op.drop_constraint('grocery_item_ibfk_2', type_='foreignkey')
        # Then drop the index
        batch_op.drop_index('ix_grocery_item')
        # Create new indexes
        batch_op.create_index(batch_op.f('ix_grocery_item_grocery_list_name_id'), ['grocery_list_name_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_item_is_active'), ['is_active'], unique=False)
        # Add new foreign key
        batch_op.create_foreign_key(None, 'grocery_list_name', ['grocery_list_name_id'], ['id'])
        # Remove column (if needed)
        batch_op.drop_column('grocery_name_id')

    with op.batch_alter_table('grocery_list_name', schema=None) as batch_op:
        batch_op.drop_index('ix_grocery_name_grocery_type')
        batch_op.drop_index('ix_grocery_name_name')
        batch_op.drop_index('ix_grocery_name_user_id')
        batch_op.create_index(batch_op.f('ix_grocery_list_name_grocery_type'), ['grocery_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_list_name_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_list_name_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=False))
        batch_op.drop_index('ix_store_product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.create_index('ix_store_product', ['store_id', 'product_id'], unique=False)
        batch_op.drop_column('unit')

    with op.batch_alter_table('grocery_list_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_user_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_name'))
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_grocery_type'))
        batch_op.create_index('ix_grocery_name_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_grocery_name_name', ['name'], unique=False)
        batch_op.create_index('ix_grocery_name_grocery_type', ['grocery_type'], unique=False)

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        # Add column back if needed
        batch_op.add_column(sa.Column('grocery_name_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        # Restore the foreign key
        batch_op.create_foreign_key('grocery_item_ibfk_2', 'grocery_list_name', ['grocery_name_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_grocery_item_is_active'))
        batch_op.drop_index(batch_op.f('ix_grocery_item_grocery_list_name_id'))
        batch_op.create_index('ix_grocery_item', ['grocery_name_id', 'item_id'], unique=False)

    # ### end Alembic commands ###
