"""empty message

Revision ID: d60f2ada0927
Revises: 6b9b1364ceed
Create Date: 2024-10-22 17:37:49.344466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd60f2ada0927'
down_revision = '6b9b1364ceed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.drop_index('ix_grocery_item')
        batch_op.create_index(batch_op.f('ix_grocery_item_grocery_list_name_id'), ['grocery_list_name_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_item_is_active'), ['is_active'], unique=False)
        batch_op.drop_constraint('grocery_item_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grocery_list_name', ['grocery_list_name_id'], ['id'])
        batch_op.drop_column('grocery_name_id')

    with op.batch_alter_table('grocery_list_name', schema=None) as batch_op:
        batch_op.drop_index('ix_grocery_name_grocery_type')
        batch_op.drop_index('ix_grocery_name_name')
        batch_op.drop_index('ix_grocery_name_user_id')
        batch_op.create_index(batch_op.f('ix_grocery_list_name_grocery_type'), ['grocery_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_list_name_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_list_name_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_product_mapping', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('grocery_list_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_user_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_name'))
        batch_op.drop_index(batch_op.f('ix_grocery_list_name_grocery_type'))
        batch_op.create_index('ix_grocery_name_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_grocery_name_name', ['name'], unique=False)
        batch_op.create_index('ix_grocery_name_grocery_type', ['grocery_type'], unique=False)

    with op.batch_alter_table('grocery_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grocery_name_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grocery_item_ibfk_2', 'grocery_list_name', ['grocery_name_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_grocery_item_is_active'))
        batch_op.drop_index(batch_op.f('ix_grocery_item_grocery_list_name_id'))
        batch_op.create_index('ix_grocery_item', ['grocery_name_id', 'item_id'], unique=False)

    # ### end Alembic commands ###
